# Generated by Django 4.0.6 on 2022-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='company_name',
            field=models.CharField(default='Asset12', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='12@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='id_number',
            field=models.CharField(default='23', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='id_proof',
            field=models.CharField(default='aadhar', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='visit_date',
            field=models.DateField(default='2022-12-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='fullname',
            field=models.CharField(max_length=40),
        ),
    ]
