# Generated by Django 4.0.6 on 2022-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_mymodel_company_name_mymodel_email_mymodel_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not specify', 'Not Specify')], default='male', max_length=20),
        ),
    ]
