# Generated by Django 4.0.6 on 2022-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_mymodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='gender',
            field=models.CharField(choices=[('-', '------'), ('male', 'Male'), ('female', 'Female'), ('not specify', 'Not Specify')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='id_proof',
            field=models.CharField(choices=[('-', '-----'), ('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('pan', 'PAN Card'), ('voterid', 'Voter ID'), ('dlicense', 'Driving License')], default='-', max_length=30),
        ),
    ]
